app/app.py
from flask import Flask, render_template, url_for, redirect, send_file,Response
from werkzeug.exceptions import HTTPException
import logging,json_logging,sys
from views import views
from google.cloud import storage



# Configure logging
logging.basicConfig(stream=sys.stdout, level=logging.INFO, format='%(asctime)s:%(levelname)s:%(message)s')

app = Flask(__name__)
app.register_blueprint(views)

json_logging.init_flask(enable_json=True)   
json_logging.init_request_instrument(app)


if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)

app/views.py
import os,re
from flask import Flask, render_template, url_for,Response, Blueprint
from werkzeug.exceptions import HTTPException
import logging
from functions import list_files_in_folder

from google.cloud import storage


currentfolder = ''

views = Blueprint('views', __name__)

@views.route('/')
def index():
    return render_template('index.html')


@views.route('/file_list/<folder>')
def file_list(folder):
    global currentfolder
    currentfolder = folder
    
    files = list_files_in_folder(f"{folder}/")

    # Extract episode number from filenames using regex and store in a dictionary
    episode_dict = {}
    for file in files:
        match = re.search(r'S\d+E(\d+)', file)
        if match:
            episode_num = match.group(1)
            episode_dict[int(episode_num)] = file

    # Sort the episode dictionary by episode number
    episode_dict = dict(sorted(episode_dict.items()))

    return render_template('episodes.html', episodes=episode_dict, seriesname=currentfolder)


@views.route('/play/<filename>')
def play(filename):
    global currentfolder

    BUCKET_NAME = os.environ.get('BUCKET_NAME')

    file_name = f'{currentfolder}/{filename}'

    client = storage.Client()

    bucket = client.get_bucket(BUCKET_NAME)
    blob = bucket.blob(file_name)

    headers = {"Range": "bytes=0-"}

    return Response(blob.download_as_bytes(), headers=headers, mimetype="video/mp4")



@views.errorhandler(Exception)
def handle_exception(error):
    # pass through HTTP errors
    if isinstance(error, HTTPException):
        return error
    logging.critical("HTTP error has occurred in: %s", error)
    # now you're handling non-HTTP exceptions only
    return render_template("404.html", error=error)

app/templates/episodes.html
<!DOCTYPE html>
<html>
<head>
	<title>File List</title>
	<link rel="stylesheet" type="text/css" href="/static/css/episodes.css">
</head>
<body>
	<h1>{{ seriesname }}</h1>

	
	<div class="file-list">
		
			


		{% if seriesname == "ChainsawMan" %}

		<div class="search-bar">
			<input type="text" id="search-input" class="search-input" placeholder="Search episodes...">
			<button type="button" class="search-button" onclick="searchEpisodes()">Search</button>
		</div>

		{% for episode_num in episodes %}
		<div class="file-item-cs episode" data-episode="{{ episode_num }}" onclick="showLoadingPopup('{{ url_for('views.play', filename=episodes[episode_num]) }}')">
			<div class="file-name">Episode {{ episode_num }}</div>
			<div class="play-button">
				<div class="play-icon"></div>
			</div>
		</div>
		
		{% endfor %}
	{% elif seriesname == "Black_Lagoon" %}
	<div class="search-bar">
		<input type="text" id="search-input" class="search-input" placeholder="Search episodes...">
		<button type="button" class="search-button" onclick="searchEpisodes()">Search</button>
	</div>
	{% for episode_num in episodes %}
		<div class="file-item-bl episode" data-episode="{{ episode_num }}" onclick="showLoadingPopup('{{ url_for('views.play', filename=episodes[episode_num]) }}')">
			<div class="file-name">Episode {{ episode_num }}</div>
			<div class="play-button">
				<div class="play-icon"></div>
			</div>
		</div>
		{% endfor %}

		{% elif seriesname == "BakiHanma" %}
		<div class="search-bar">
			<input type="text" id="search-input" class="search-input" placeholder="Search episodes...">
			<button type="button" class="search-button" onclick="searchEpisodes()">Search</button>
		</div>
		{% for episode_num in episodes %}
			<div class="file-item-bh episode" data-episode="{{ episode_num }}" onclick="showLoadingPopup('{{ url_for('views.play', filename=episodes[episode_num]) }}')">
				<div class="file-name">Episode {{ episode_num }}</div>
				<div class="play-button">
					<div class="play-icon"></div>
				</div>
			</div>
			{% endfor %}
		{% elif seriesname == "Dr.Stone" %}
		<div class="search-bar">
			<input type="text" id="search-input" class="search-input" placeholder="Search episodes...">
			<button type="button" class="search-button" onclick="searchEpisodes()">Search</button>
		</div>
		{% for episode_num in episodes %}
			<div class="file-item-ds episode" data-episode="{{ episode_num }}" onclick="showLoadingPopup('{{ url_for('views.play', filename=episodes[episode_num]) }}')">
				<div class="file-name">Episode {{ episode_num }}</div>
				<div class="play-button">
					<div class="play-icon"></div>
				</div>
			</div>
			{% endfor %}
			{% elif seriesname == "AOT" %}
		<div class="search-bar">
			<input type="text" id="search-input" class="search-input" placeholder="Search episodes...">
			<button type="button" class="search-button" onclick="searchEpisodes()">Search</button>
		</div>
		{% for episode_num in episodes %}
			<div class="file-item-aot episode" data-episode="{{ episode_num }}" onclick="showLoadingPopup('{{ url_for('views.play', filename=episodes[episode_num]) }}')">
				<div class="file-name">Episode {{ episode_num }}</div>
				<div class="play-button">
					<div class="play-icon"></div>
				</div>
			</div>
			{% endfor %}
	{% else %}
	<div class="search-bar">
		<input type="text" id="search-input" class="search-input" placeholder="Search episodes...">
		<button type="button" class="search-button" onclick="searchEpisodes()">Search</button>
	</div>

	{% for episode_num in episodes %}
		<div class="file-item-cb episode" data-episode="{{ episode_num }}" onclick="showLoadingPopup('{{ url_for('views.play', filename=episodes[episode_num]) }}')">
			<div class="file-name">Episode {{ episode_num }}</div>
			<div class="play-button">
				<div class="play-icon"></div>
			</div>
		</div>
		{% endfor %}
	{% endif %}
	



	
	</div>
	
	<script>
		function showLoadingPopup(url) {
			var popup = document.createElement('div');
			popup.classList.add('loading-popup');
			popup.innerHTML = '<div class="spinner"></div><div class="message">Loading. Please wait...</div>';
			document.body.appendChild(popup);

			setTimeout(function() {
				window.location.href = url;
			}, 3000);
		}

		function searchEpisodes() {
			// Get the input value
			var input = document.getElementById("search-input").value.toLowerCase();
	
			// Get all the episode items
			var episodes = document.getElementsByClassName("episode");
	
			// Loop through all the episode items and hide/show them based on the search query
			for (var i = 0; i < episodes.length; i++) {
				var episode = episodes[i];
				var episodeNum = episode.getAttribute("data-episode");
				if (episodeNum.toLowerCase().indexOf(input) > -1) {
					episode.style.display = "";
				} else {
					episode.style.display = "none";
				}
			}
		}
	</script>
	</body>
</html>
	

app/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>My Website</title>
	<style>
		body {
			background-color: #111;
			color: #fff;
			font-family: Arial, sans-serif;
			font-size: 16px;
			margin: 0;
			padding: 0;
		}
		header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		padding: 20px;
		background-color: #222;
	}

	header img {
		max-width: 100%;
		height: auto;
	}

	nav ul {
		display: flex;
		list-style: none;
		margin: 0;
		padding: 0;
	}

	nav li {
		margin-right: 20px;
	}

	nav li:last-child {
		margin-right: 0;
	}

	nav a {
		color: #fff;
		text-decoration: none;
		font-weight: bold;
		transition: all 0.3s ease;
	}

	nav a:hover {
		color: #ccc;
	}

	.container {
		display: flex;
		flex-wrap: wrap;
		height: calc(100vh - 100px);
		justify-content: center;
		align-items: center;
	}


	.container div {
		flex-basis: calc(100%/3);
		height: calc(100%/2);
		position: relative;
		overflow: hidden;
		cursor: pointer;
		transition: all 0.3s ease;
	}

	.container div img {
		width: 100%;
		height: 100%;
		position: absolute;
		top: 0;
		left: 0;
		transition: all 0.3s ease;
		object-fit: cover;
		border: 4px solid black; /* Add this line */
		box-sizing: border-box; /* Add this line to include the border in the size calculation */
		}


	.container div:hover img {
		filter: brightness(70%);
	}

	.container div a {
		display: block;
		position: absolute;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
	}
</style>
<body>
	<header>
		<img src="https://i.imgur.com/9wN2JZf.png" alt="Logo">
		<nav>
			<ul>
				<li><a href="#">Home</a></li>
				<li><a href="#">About</a></li>
				<li><a href="#">Contact</a></li>
			</ul>
		</nav>
	</header>
	<div class="container">
		<div>
			<a href="/file_list/Black_Lagoon">
				<img src="https://www.theanimedaily.com/wp-content/uploads/2021/03/Black-Lagoon-Season-4-3.jpg" alt="Image 1">
			</a>
		</div>
		<div>
			<a href="/file_list/ChainsawMan">
				<img src="https://img1.ak.crunchyroll.com/i/spire4/f91275e6e5a3c15be90358c6ead433ca1659084308_main.png" alt="Image 2">
			</a>
		</div>
		<div>
			<a href="/file_list/CowboyBebop">
				<img src="https://img.olhardigital.com.br/wp-content/uploads/2021/06/fun-FUN-CBY-JPN_S1-Full-Image_GalleryCover-en-US-1489784785929._UR19201080_RI_.jpg" alt="Image 3">
			</a>
		</div>
		<div>
			<a href="/file_list/BakiHanma">
				<img src="https://occ-0-2568-58.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABUbolrsi2liOMO4EWmHoWAIuzTpefasoKDVN0GSY4WxOoo9OCTGCd_y2ysAfKdaxmLaafS7Upvd0Y4Nw8Hd6I31jS51xbB06Jkxz6OR20J6FRkmja9sIj1WuCE5aLzF5rd0Lyw.jpg?r=be3" alt="Image 4">
			</a>
		</div>
		<div>
			<a href="/file_list/Dr.Stone">
				<img src="https://i.imgur.com/swNmOYl.jpg" alt="Image 5">
			</a>
		</div>
		<div>
			<a href="/file_list/AOT">
				<img src="https://www.thenewsfetcher.com/wp-content/uploads/2020/11/attack-on-titan-cover.jpg" alt="Image 6">
			</a>
		</div>
	</div>
</body>
</html>